# Site settings
name: Zzzxb's blog
description: 你要静心学习那份等待时机的成熟的情绪，也要你一定保有这份等待之外的努力和坚持。
author: 赵赵赵小白
email: idearfree@outlook.com
url: https://zzzxb.xyz
resume_site: 
github: https://github.com/zzzxb
baseurl: ""
meta_description: 你要静心学习那份等待时机的成熟的情绪，也要你一定保有这份等待之外的努力和坚持。
motto: 远方有多远,请你告诉我!
banner: 我从未如此热爱我的生活.
permalink: /404.html
#theme: jekyll-theme-cayman

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Zzzxb

# Build settings
markdown: kramdown

baidu_analysis: de8709405abc7f73e4e3e5dd34941f66