# Site settings
name: Zzzxb's blog
email: idearfree@outlook.com
author: 赵赵赵小白
url: https://www.idearfree.com
resume_site: 
github: https://github.com/zzzxb
baseurl: ""
description: 我从未如此热爱我的生活.
meta_description: 远方有多远,请你告诉我!
motto: 远方有多远,请你告诉我!
banner: 我从未如此热爱我的生活.
permalink: /404.html
#theme: jekyll-theme-cayman

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Zzzxb

# Build settings
markdown: kramdown

baidu_analysis: de8709405abc7f73e4e3e5dd34941f66