# Site settings
name: 赵小白的博客
email: idearfree@outlook.com
author: 赵赵赵小白
url: https://www.idearfree.com
resume_site: 
github: https://github.com/zzzxb
baseurl: "/LessOrMore"
description: 砥砺前行，生活不止眼前的苟且。
meta_description: 远方有多远,请你告诉我!
motto: 远方有多远,请你告诉我!
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Zzzxb

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

